# Generated by Django 6.0 on 2026-05-26 13:54

import App.services.profile_photo_storage
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogViewer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'All logs',
                'verbose_name_plural': 'All logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=500)),
                ('object_id', models.CharField(max_length=500)),
                ('object_repr', models.CharField(max_length=500)),
                ('action', models.CharField(default='CHANGE', max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changes', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'All admin audit',
                'verbose_name_plural': 'All admin audit',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdminEmailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('onboarding', 'Onboarding email'), ('force_password', 'Force password email'), ('reminder', 'Reminder email'), ('login_lock', 'Login lock email'), ('login_unlock', 'Login unlock email')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_failures', 'Completed with failures'), ('failed', 'Failed')], db_index=True, default='queued', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('queued_count', models.PositiveIntegerField(default=0)),
                ('running_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Admin email job',
                'verbose_name_plural': 'Admin email jobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('DIRECT', 'Direct Message')], max_length=20)),
                ('audience_role', models.CharField(blank=True, choices=[('HR', 'HR'), ('EMPLOYEE', 'Employee'), ('Admin', 'Admin')], max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_optional', models.BooleanField(default=False, help_text='If True, employees may choose whether to apply leave.')),
            ],
            options={
                'verbose_name': 'Company Holiday',
                'verbose_name_plural': 'Company Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Short', 'Short'), ('Half', 'Half'), ('Unpaid', 'Unpaid'), ('Sick', 'Sick'), ('Earned', 'Earned')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('requested_from_date', models.DateField(blank=True, null=True)),
                ('requested_to_date', models.DateField(blank=True, null=True)),
                ('admin_skip_wfh_bridge', models.BooleanField(default=False, help_text='Admin-only override to keep this leave out of WFH bridge auto-expansion.')),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('reason', models.TextField()),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('no_of_times_updated', models.PositiveIntegerField(default=0)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('deducted_from', models.CharField(choices=[('Earned', 'Earned'), ('Sick', 'Sick'), ('Unpaid', 'Unpaid'), ('None', 'None')], default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leave_balance', models.FloatField(default=27)),
                ('total_leave_remaining', models.FloatField(default=27)),
                ('sick_total', models.FloatField(default=12)),
                ('sick_used', models.FloatField(default=0)),
                ('earned_total', models.FloatField(default=15)),
                ('earned_used', models.FloatField(default=0)),
                ('unpaid', models.FloatField(default=0)),
                ('last_year_end_processed', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFromHomeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work From Home Day',
                'verbose_name_plural': 'Work From Home Days',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='YearEndCarryForwardRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Year-end carry forward run',
                'verbose_name_plural': 'Year-end carry forward',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Analytics logs',
                'verbose_name_plural': 'Analytics logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='ApiLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'API logs',
                'verbose_name_plural': 'API logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='AuthLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Authentication logs',
                'verbose_name_plural': 'Authentication logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='BackupLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Backup logs',
                'verbose_name_plural': 'Backup logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='BackupRestoreControl',
            fields=[
            ],
            options={
                'verbose_name': 'Backup restore',
                'verbose_name_plural': 'Backup restore',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='DashboardSummaryControl',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard summary',
                'verbose_name_plural': 'Dashboard summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='DjangoErrorLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Django error logs',
                'verbose_name_plural': 'Django error logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='EmailLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Raw email file logs',
                'verbose_name_plural': 'Raw email file logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='LeaveLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Leave logs',
                'verbose_name_plural': 'Leave logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='MaintenanceLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Maintenance logs',
                'verbose_name_plural': 'Maintenance logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='MaintenanceModeControl',
            fields=[
            ],
            options={
                'verbose_name': 'Maintenance mode',
                'verbose_name_plural': 'Maintenance mode',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='MasterLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Master logs',
                'verbose_name_plural': 'Master logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='ProfileLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Profile logs',
                'verbose_name_plural': 'Profile logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='ReportExportControl',
            fields=[
            ],
            options={
                'verbose_name': 'Report export center',
                'verbose_name_plural': 'Report export center',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='SchedulerLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Scheduler logs',
                'verbose_name_plural': 'Scheduler logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='SecurityLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Security logs',
                'verbose_name_plural': 'Security logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='ServiceActionControl',
            fields=[
            ],
            options={
                'verbose_name': 'Service actions',
                'verbose_name_plural': 'Service actions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='ServiceLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Service logs',
                'verbose_name_plural': 'Service logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='SystemHealthControl',
            fields=[
            ],
            options={
                'verbose_name': 'System health',
                'verbose_name_plural': 'System health',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='AdminCommunicationAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Admin communication audit',
                'verbose_name_plural': 'Admin communication audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='AllCommunicationNotificationAudit',
            fields=[
            ],
            options={
                'verbose_name': 'All communication notification audit',
                'verbose_name_plural': 'All communication notification audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='DeleteAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Delete audit',
                'verbose_name_plural': 'Delete audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='EmployeeCommunicationAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Employee communication audit',
                'verbose_name_plural': 'Employee communication audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='EmployeeCommunicationReadSeenAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Employee communication read/seen audit',
                'verbose_name_plural': 'Employee communication read/seen audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveNotificationReadSeenAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Employee leave notification read/seen audit',
                'verbose_name_plural': 'Employee leave notification read/seen audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='HolidayAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Holiday audit',
                'verbose_name_plural': 'Holiday audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='HRCommunicationAudit',
            fields=[
            ],
            options={
                'verbose_name': 'HR communication audit',
                'verbose_name_plural': 'HR communication audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='HRCommunicationReadSeenAudit',
            fields=[
            ],
            options={
                'verbose_name': 'HR communication read/seen audit',
                'verbose_name_plural': 'HR communication read/seen audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='HRLeaveNotificationReadSeenAudit',
            fields=[
            ],
            options={
                'verbose_name': 'HR leave notification read/seen audit',
                'verbose_name_plural': 'HR leave notification read/seen audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='LeaveAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Leave audit',
                'verbose_name_plural': 'Leave audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='ProfileAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Profile audit',
                'verbose_name_plural': 'Profile audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='UserAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'User audit',
                'verbose_name_plural': 'User audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='WorkFromHomeAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Work from home audit',
                'verbose_name_plural': 'Work from home audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='AdminCommunicationCenter',
            fields=[
            ],
            options={
                'verbose_name': 'Admin communication center',
                'verbose_name_plural': 'Admin communication center',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communication',),
        ),
        migrations.CreateModel(
            name='EmployeeCommunication',
            fields=[
            ],
            options={
                'verbose_name': 'Employee communication',
                'verbose_name_plural': 'Employee communications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communication',),
        ),
        migrations.CreateModel(
            name='HRCommunication',
            fields=[
            ],
            options={
                'verbose_name': 'HR communication',
                'verbose_name_plural': 'HR communications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communication',),
        ),
        migrations.CreateModel(
            name='CommunicationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='App.communication')),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCommunicationRead',
            fields=[
            ],
            options={
                'verbose_name': 'Employee communication read',
                'verbose_name_plural': 'Employee communication reads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communicationread',),
        ),
        migrations.CreateModel(
            name='HRCommunicationRead',
            fields=[
            ],
            options={
                'verbose_name': 'HR communication read',
                'verbose_name_plural': 'HR communication reads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communicationread',),
        ),
        migrations.CreateModel(
            name='CommunicationSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_receipts', to='App.communication')),
            ],
            options={
                'ordering': ['-seen_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCommunicationSeen',
            fields=[
            ],
            options={
                'verbose_name': 'Employee communication seen',
                'verbose_name_plural': 'Employee communication seen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communicationseen',),
        ),
        migrations.CreateModel(
            name='HRCommunicationSeen',
            fields=[
            ],
            options={
                'verbose_name': 'HR communication seen',
                'verbose_name_plural': 'HR communication seen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communicationseen',),
        ),
        migrations.CreateModel(
            name='LeaveBalanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('changes', models.JSONField(default=dict)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='App.leavebalance')),
            ],
            options={
                'verbose_name': 'Leave balance audit entry',
                'verbose_name_plural': 'Leave balance audit entries',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalanceAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Leave balance audit',
                'verbose_name_plural': 'Leave balance audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.leavebalanceaudit',),
        ),
        migrations.CreateModel(
            name='LeaveNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='App.leave')),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveNotificationRead',
            fields=[
            ],
            options={
                'verbose_name': 'Employee leave notification read',
                'verbose_name_plural': 'Employee leave notification reads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.leavenotificationread',),
        ),
        migrations.CreateModel(
            name='HRLeaveNotificationRead',
            fields=[
            ],
            options={
                'verbose_name': 'HR leave notification read',
                'verbose_name_plural': 'HR leave notification reads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.leavenotificationread',),
        ),
        migrations.CreateModel(
            name='LeaveNotificationSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_seen_receipts', to='App.leave')),
            ],
            options={
                'ordering': ['-seen_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveNotificationSeen',
            fields=[
            ],
            options={
                'verbose_name': 'Employee leave notification seen',
                'verbose_name_plural': 'Employee leave notification seen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.leavenotificationseen',),
        ),
        migrations.CreateModel(
            name='HRLeaveNotificationSeen',
            fields=[
            ],
            options={
                'verbose_name': 'HR leave notification seen',
                'verbose_name_plural': 'HR leave notification seen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.leavenotificationseen',),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('must_change_password', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('date_of_joining', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('address', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, default=None, null=True, storage=App.services.profile_photo_storage.ProfilePhotoStorage(), upload_to='profile_photos/')),
                ('profile_photo_update_count', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('welcome_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='leavenotificationseen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_notification_seen_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavenotificationread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_notification_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavebalanceaudit',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance_audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavebalanceaudit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_balance_updates_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leave',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(db_index=True, max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('from_email', models.CharField(blank=True, max_length=500)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery_logs', to='App.leave')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery_logs_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email delivery history',
                'verbose_name_plural': 'Email delivery history',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='communicationseen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_seen_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdminEmailJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=50)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App.adminemailjob')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_email_job_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin email job item',
                'verbose_name_plural': 'Admin email job items',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='adminemailjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_email_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('browser', models.CharField(blank=True, max_length=120)),
                ('device_label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push subscription',
                'verbose_name_plural': 'Push subscriptions',
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='App_pushsub_user_id_28d7f5_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='leavenotificationseen',
            unique_together={('user', 'leave')},
        ),
        migrations.AlterUniqueTogether(
            name='leavenotificationread',
            unique_together={('user', 'leave')},
        ),
        migrations.AlterUniqueTogether(
            name='communicationseen',
            unique_together={('user', 'communication')},
        ),
        migrations.AlterUniqueTogether(
            name='communicationread',
            unique_together={('user', 'communication')},
        ),
    ]
