# Generated by Django 6.0 on 2026-05-26 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('onboarding', 'Onboarding email'), ('force_password', 'Force password email'), ('reminder', 'Reminder email')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_failures', 'Completed with failures'), ('failed', 'Failed')], db_index=True, default='queued', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('queued_count', models.PositiveIntegerField(default=0)),
                ('running_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_email_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin email job',
                'verbose_name_plural': 'Admin email jobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdminEmailJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=50)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App.adminemailjob')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_email_job_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin email job item',
                'verbose_name_plural': 'Admin email job items',
                'ordering': ['id'],
            },
        ),
    ]
