# Generated by Django 6.0.1 on 2026-03-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='sick_total',
            field=models.FloatField(default=12),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_leaves',
            field=models.FloatField(default=27),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_photos/'),
        ),
    ]
