# Generated by Django 6.0 on 2026-04-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_leave_requested_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearEndCarryForwardRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Year-end carry forward run',
                'verbose_name_plural': 'Year-end carry forward runs',
                'ordering': ['-year'],
            },
        ),
    ]
