# Generated by Django 6.0 on 2026-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_adminemailjob_adminemailjobitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminemailjob',
            name='job_type',
            field=models.CharField(choices=[('onboarding', 'Onboarding email'), ('force_password', 'Force password email'), ('reminder', 'Reminder email'), ('login_lock', 'Login lock email'), ('login_unlock', 'Login unlock email')], db_index=True, max_length=50),
        ),
    ]
