# Generated by Django 6.0 on 2026-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_yearendcarryforwardrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='last_year_end_processed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
