# Generated by Django 6.0 on 2026-04-19 12:17

from django.db import migrations, models


def backfill_leave_balance_totals(apps, schema_editor):
    LeaveBalance = apps.get_model("App", "LeaveBalance")

    for balance in LeaveBalance.objects.all():
        total_balance = float(balance.sick_total or 0) + float(balance.earned_total or 0)
        total_remaining = float(balance.total_leaves or 0)

        balance.total_leave_balance = total_balance
        balance.total_leave_remaining = max(total_remaining, 0)
        balance.save(update_fields=["total_leave_balance", "total_leave_remaining"])


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_leavebalance_last_year_end_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='total_leave_balance',
            field=models.FloatField(default=27),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='total_leave_remaining',
            field=models.FloatField(default=27),
        ),
        migrations.RunPython(backfill_leave_balance_totals, migrations.RunPython.noop),
    ]
