# Generated by Django 6.0 on 2026-04-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_leavebalance_total_leave_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='total_leaves',
        ),
    ]
