# Generated by Django 6.0 on 2026-04-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_leave_status_datetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Short', 'Short'), ('Half', 'Half'), ('Unpaid', 'Unpaid'), ('Sick', 'Sick'), ('Earned', 'Earned')], max_length=20),
        ),
    ]
