# Generated by Django 6.0 on 2026-04-15 05:43

from django.db import migrations


def rename_casual_to_unpaid(apps, schema_editor):
    Leave = apps.get_model('App', 'Leave')
    Leave.objects.filter(leave_type='Casual').update(leave_type='Unpaid')


def rename_unpaid_to_casual(apps, schema_editor):
    Leave = apps.get_model('App', 'Leave')
    Leave.objects.filter(leave_type='Unpaid').update(leave_type='Casual')


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_casual_to_unpaid'),
    ]

    operations = [
        migrations.RunPython(rename_casual_to_unpaid, rename_unpaid_to_casual),
    ]
