# Generated by Django 6.0 on 2026-05-18 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_leave_reviewed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('changes', models.JSONField(default=dict)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='App.leavebalance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_balance_updates_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave balance audit entry',
                'verbose_name_plural': 'Leave balance audit entries',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
