# Generated by Django 6.0 on 2026-05-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_adminauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Holiday audit',
                'verbose_name_plural': 'Holiday audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='LeaveAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Leave audit',
                'verbose_name_plural': 'Leave audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='LeaveBalanceAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Leave balance audit',
                'verbose_name_plural': 'Leave balance audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.leavebalanceaudit',),
        ),
        migrations.CreateModel(
            name='ProfileAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Profile audit',
                'verbose_name_plural': 'Profile audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='UserAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'User audit',
                'verbose_name_plural': 'User audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='WorkFromHomeAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Work from home audit',
                'verbose_name_plural': 'Work from home audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.AlterModelOptions(
            name='adminauditlog',
            options={'ordering': ['-changed_at', '-id'], 'verbose_name': 'All admin audit', 'verbose_name_plural': 'All admin audit'},
        ),
    ]
