# Generated by Django 6.0 on 2026-05-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_holidayadminaudit_leaveadminaudit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearendcarryforwardrun',
            options={'ordering': ['-year'], 'verbose_name': 'Year-end carry forward run', 'verbose_name_plural': 'Year-end carry forward'},
        ),
    ]
