# Generated by Django 6.0 on 2026-05-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_yearendcarryforwardrun_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCommunication',
            fields=[
            ],
            options={
                'verbose_name': 'Employee communication',
                'verbose_name_plural': 'Employee communications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communication',),
        ),
        migrations.CreateModel(
            name='EmployeeCommunicationRead',
            fields=[
            ],
            options={
                'verbose_name': 'Employee communication read',
                'verbose_name_plural': 'Employee communication reads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communicationread',),
        ),
        migrations.CreateModel(
            name='EmployeeCommunicationSeen',
            fields=[
            ],
            options={
                'verbose_name': 'Employee communication seen',
                'verbose_name_plural': 'Employee communication seen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communicationseen',),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveNotificationRead',
            fields=[
            ],
            options={
                'verbose_name': 'Employee leave notification read',
                'verbose_name_plural': 'Employee leave notification reads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.leavenotificationread',),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveNotificationSeen',
            fields=[
            ],
            options={
                'verbose_name': 'Employee leave notification seen',
                'verbose_name_plural': 'Employee leave notification seen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.leavenotificationseen',),
        ),
        migrations.CreateModel(
            name='HRCommunication',
            fields=[
            ],
            options={
                'verbose_name': 'HR communication',
                'verbose_name_plural': 'HR communications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communication',),
        ),
        migrations.CreateModel(
            name='HRCommunicationRead',
            fields=[
            ],
            options={
                'verbose_name': 'HR communication read',
                'verbose_name_plural': 'HR communication reads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communicationread',),
        ),
        migrations.CreateModel(
            name='HRCommunicationSeen',
            fields=[
            ],
            options={
                'verbose_name': 'HR communication seen',
                'verbose_name_plural': 'HR communication seen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communicationseen',),
        ),
        migrations.CreateModel(
            name='HRLeaveNotificationRead',
            fields=[
            ],
            options={
                'verbose_name': 'HR leave notification read',
                'verbose_name_plural': 'HR leave notification reads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.leavenotificationread',),
        ),
        migrations.CreateModel(
            name='HRLeaveNotificationSeen',
            fields=[
            ],
            options={
                'verbose_name': 'HR leave notification seen',
                'verbose_name_plural': 'HR leave notification seen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.leavenotificationseen',),
        ),
    ]
