# Generated by Django 6.0 on 2026-05-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_employeecommunication_employeecommunicationread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCommunicationNotificationAudit',
            fields=[
            ],
            options={
                'verbose_name': 'All communication notification audit',
                'verbose_name_plural': 'All communication notification audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='EmployeeCommunicationAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Employee communication audit',
                'verbose_name_plural': 'Employee communication audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='EmployeeCommunicationReadSeenAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Employee communication read/seen audit',
                'verbose_name_plural': 'Employee communication read/seen audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveNotificationReadSeenAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Employee leave notification read/seen audit',
                'verbose_name_plural': 'Employee leave notification read/seen audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='HRCommunicationAudit',
            fields=[
            ],
            options={
                'verbose_name': 'HR communication audit',
                'verbose_name_plural': 'HR communication audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='HRCommunicationReadSeenAudit',
            fields=[
            ],
            options={
                'verbose_name': 'HR communication read/seen audit',
                'verbose_name_plural': 'HR communication read/seen audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
        migrations.CreateModel(
            name='HRLeaveNotificationReadSeenAudit',
            fields=[
            ],
            options={
                'verbose_name': 'HR leave notification read/seen audit',
                'verbose_name_plural': 'HR leave notification read/seen audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
    ]
