# Generated by Django 6.0 on 2026-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_allcommunicationnotificationaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogViewer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'All logs',
                'verbose_name_plural': 'All logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticsLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Analytics logs',
                'verbose_name_plural': 'Analytics logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='ApiLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'API logs',
                'verbose_name_plural': 'API logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='AuthLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Authentication logs',
                'verbose_name_plural': 'Authentication logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='BackupLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Backup logs',
                'verbose_name_plural': 'Backup logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='DjangoErrorLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Django error logs',
                'verbose_name_plural': 'Django error logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='EmailLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Email logs',
                'verbose_name_plural': 'Email logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='LeaveLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Leave logs',
                'verbose_name_plural': 'Leave logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='MasterLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Master logs',
                'verbose_name_plural': 'Master logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='ProfileLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Profile logs',
                'verbose_name_plural': 'Profile logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='SchedulerLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Scheduler logs',
                'verbose_name_plural': 'Scheduler logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
        migrations.CreateModel(
            name='SecurityLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Security logs',
                'verbose_name_plural': 'Security logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
    ]
