# Generated by Django 6.0 on 2026-05-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_logviewer_analyticslogviewer_apilogviewer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAdminAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Delete audit',
                'verbose_name_plural': 'Delete audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
    ]
