# Generated by Django 6.0 on 2026-05-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_deleteadminaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRestoreControl',
            fields=[
            ],
            options={
                'verbose_name': 'Backup restore',
                'verbose_name_plural': 'Backup restore',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
    ]
