# Generated by Django 6.0 on 2026-05-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_backuprestorecontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceModeControl',
            fields=[
            ],
            options={
                'verbose_name': 'Maintenance mode',
                'verbose_name_plural': 'Maintenance mode',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
    ]
