# Generated by Django 6.0 on 2026-05-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_maintenancemodecontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Maintenance logs',
                'verbose_name_plural': 'Maintenance logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
    ]
