# Generated by Django 6.0 on 2026-05-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_maintenancelogviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLogViewer',
            fields=[
            ],
            options={
                'verbose_name': 'Service logs',
                'verbose_name_plural': 'Service logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
    ]
