# Generated by Django 6.0 on 2026-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_serviceactioncontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCommunicationCenter',
            fields=[
            ],
            options={
                'verbose_name': 'Admin communication center',
                'verbose_name_plural': 'Admin communication center',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.communication',),
        ),
        migrations.AlterField(
            model_name='communication',
            name='audience_role',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('EMPLOYEE', 'Employee'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
