# Generated by Django 6.0 on 2026-05-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_admincommunicationcenter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCommunicationAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Admin communication audit',
                'verbose_name_plural': 'Admin communication audit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.adminauditlog',),
        ),
    ]
