# Generated by Django 6.0 on 2026-05-20 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_leave_admin_skip_wfh_bridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(db_index=True, max_length=80)),
                ('subject', models.CharField(max_length=255)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery_logs', to='App.leave')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery_logs_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email delivery log',
                'verbose_name_plural': 'Email delivery logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
