# Generated by Django 6.0 on 2026-05-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_emaildeliverylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaildeliverylog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Email delivery history', 'verbose_name_plural': 'Email delivery history'},
        ),
        migrations.AlterModelOptions(
            name='emaillogviewer',
            options={'verbose_name': 'Raw email file logs', 'verbose_name_plural': 'Raw email file logs'},
        ),
    ]
