# Generated by Django 6.0 on 2026-05-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_alter_emaildeliverylog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthControl',
            fields=[
            ],
            options={
                'verbose_name': 'System health',
                'verbose_name_plural': 'System health',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
    ]
