# Generated by Django 6.0 on 2026-05-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_systemhealthcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportControl',
            fields=[
            ],
            options={
                'verbose_name': 'Report export center',
                'verbose_name_plural': 'Report export center',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
    ]
