# Generated by Django 6.0 on 2026-05-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_profile_welcome_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSummaryControl',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard summary',
                'verbose_name_plural': 'Dashboard summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('App.logviewer',),
        ),
    ]
