# Generated by Django 6.0 on 2026-05-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_dashboardsummarycontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
